import { initTheme, getThemeChoice, setTheme } from './theme.js';
import { setLanguage } from './i18n.js';
import { changeQuantity, getCart, removeFromCart } from './cart.js';
import { initSearch } from './search.js';
import { initCarousels } from './carousel.js';
import { initHeaderInteractions } from './layout.js';
import { loadPartial } from './partials.js';
import { renderIcons } from './icons.js';

const productsUrl = new URL('./data/products.json', import.meta.url);
const loadProducts = () => fetch(productsUrl).then((response) => response.json());
const currency = (value) => new Intl.NumberFormat(document.documentElement.lang || 'fr', { style: 'currency', currency: 'EUR' }).format(value);
const card = (product) => `<article class="product-card" data-product-card><div class="product-placeholder" aria-hidden="true"></div><div class="product-card__body"><p>${product.category}</p><h3>${product.name}</h3><p class="price">${currency(product.price)}</p><a class="button" href="produit.html?id=${product.id}">Voir le produit</a></div></article>`;
function initVideoObserver() { const videos = document.querySelectorAll('video[data-lazy-video]'); if (!videos.length) return; const observer = new IntersectionObserver((entries) => entries.forEach(({ target, isIntersecting }) => isIntersecting ? target.play().catch(() => {}) : target.pause()), { threshold: .15 }); videos.forEach((video) => { video.pause(); observer.observe(video); }); }
async function renderProducts() { const target = document.querySelector('[data-products]'); if (!target) return; target.innerHTML = (await loadProducts()).map(card).join(''); }
async function renderProductPage() { const target = document.querySelector('[data-product-detail]'); if (!target) return; const products = await loadProducts(); const id = new URLSearchParams(location.search).get('id') || '1'; const product = products.find((item) => item.id === id) || products[0]; target.innerHTML = `<div class="media-frame"><video class="product-video" data-lazy-video autoplay loop muted playsinline><source src="assets/videos/parfum3D.mp4" type="video/mp4"></video></div><div><p>${product.category}</p><h1>${product.name}</h1><p class="price">${currency(product.price)}</p><p>${product.description}</p><div class="quantity-control"><button data-detail-change="-1" aria-label="Diminuer"><i data-lucide="minus"></i></button><span data-detail-quantity>0</span><button data-detail-change="1" aria-label="Augmenter"><i data-lucide="plus"></i></button></div> <button class="button button--accent" data-add-product="${product.id}">Ajouter au panier</button></div>`; const refresh = () => { document.querySelector('[data-detail-quantity]').textContent = getCart().find((item) => item.id === product.id)?.quantity || 0; }; target.addEventListener('click', (event) => { const amount = event.target.closest('[data-detail-change]')?.dataset.detailChange; if (amount) { changeQuantity(product.id, Number(amount)); refresh(); } if (event.target.closest('[data-add-product]')) { changeQuantity(product.id, 1); refresh(); } }); refresh(); renderIcons(); initVideoObserver(); }
async function renderCart() { const target = document.querySelector('[data-cart-items]'); if (!target) return; const products = await loadProducts(); const cart = getCart(); if (!cart.length) { target.innerHTML = '<p class="empty-state">Votre panier est vide.</p>'; return; } target.innerHTML = cart.map((item) => { const product = products.find((p) => p.id === item.id); return `<article class="cart-row"><div><h2>${product.name}</h2><p class="price">${currency(product.price)}</p></div><div><div class="quantity-control"><button data-cart-action="minus" data-id="${item.id}" aria-label="Diminuer"><i data-lucide="minus"></i></button><span>${item.quantity}</span><button data-cart-action="plus" data-id="${item.id}" aria-label="Augmenter"><i data-lucide="plus"></i></button></div><button class="icon-button" data-cart-action="remove" data-id="${item.id}">Supprimer</button></div></article>`; }).join(''); renderIcons(); target.onclick = (event) => { const control = event.target.closest('[data-cart-action]'); if (!control) return; const { cartAction: action, id } = control.dataset; if (action === 'plus') changeQuantity(id, 1); if (action === 'minus') changeQuantity(id, -1); if (action === 'remove') removeFromCart(id); renderCart(); }; }
function initThemeMenu() { const toggle = document.querySelector('[data-theme-toggle]'); const menu = document.querySelector('[data-theme-menu]'); const icons = { light: 'sun', dark: 'moon', system: 'monitor' }; const refresh = () => { const choice = getThemeChoice(); const previous = document.querySelector('[data-theme-icon]'); previous.outerHTML = `<i data-theme-icon data-lucide="${icons[choice]}"></i>`; document.querySelectorAll('[data-theme-option]').forEach((option) => option.classList.toggle('is-active', option.dataset.themeOption === choice)); renderIcons(); }; toggle.addEventListener('click', () => { const open = menu.hidden; menu.hidden = !open; toggle.setAttribute('aria-expanded', String(open)); }); menu.addEventListener('click', (event) => { const choice = event.target.dataset.themeOption; if (!choice) return; setTheme(choice); refresh(); menu.hidden = true; toggle.setAttribute('aria-expanded', 'false'); }); document.addEventListener('click', (event) => { if (!event.target.closest('.theme-control')) { menu.hidden = true; toggle.setAttribute('aria-expanded', 'false'); } }); refresh(); }
document.addEventListener('DOMContentLoaded', async () => { initTheme(); try { await Promise.all([loadPartial('#header-slot', '/src/partials/header.html'), loadPartial('#footer-slot', '/src/partials/footer.html')]); initHeaderInteractions(); initThemeMenu(); const language = localStorage.getItem('ebene-language') || 'fr'; await setLanguage(language); document.querySelector('[data-language]').value = language; document.querySelector('[data-language]').addEventListener('change', (event) => setLanguage(event.target.value)); document.addEventListener('cartchange', () => renderCart()); initSearch(); initCarousels(); initVideoObserver(); renderIcons(); await renderProducts(); await renderProductPage(); await renderCart(); } finally { document.body.classList.remove('is-loading'); document.body.classList.add('is-ready'); } });
